### ISSUE TITLE
Difference with pybindGen

### ISSUE THREAD

**Issue by arita291** [wjakob/pybind11#104]
Hello,
Thanks for making such binder.
This is not an issue, but:

Wondering the differences between the other Python based binder:
http://pythonhosted.org/PyBindGen/

Thanks

**Comment by wjakob** [comment]
Pybindgen generates C++ code and then compiles that in 2 passes, pybind11 uses templates & the type system to infer that code within the compiler in 1 pass.

**Comment by arita291** [comment]
But, PyBindGen is in python and pybind11 is in C++ (writing C++ code).
Do you have any benchmarks about code generated by PyBind11 ? tahnks

**Comment by wjakob** [comment]
it's all in the documentation....
