### ISSUE TITLE
Cannot use void pointer in virtual method argument

### ISSUE THREAD

**Issue by nbigaouette** [wjakob/pybind11#106]
Some virtual methods I'm trying to expose contains a `void *` argument but trying to wrap it using `PYBIND11_OVERLOAD` fails.

For example, modifying example12.cpp as such:

     $ diff --git a/example/example12.cpp b/example/example12.cpp
    index 57a0765..48641b9 100644
    --- a/example/example12.cpp
    +++ b/example/example12.cpp
    @@ -27,6 +27,11 @@ public:
             return state + value;
         }
     
    +    virtual void test(void *voidArgument)
    +    {
    +        std::cout << "test()" << std::endl;
    +    }
    +
         virtual void pure_virtual() = 0;
     private:
         int state;
    @@ -47,6 +52,16 @@ public:
             );
         }
     
    +    virtual void test(void *test) {
    +        /* Generate wrapping code that enables native function overloading */
    +        PYBIND11_OVERLOAD(
    +            void,        /* Return type */
    +            Example12,  /* Parent class */
    +            test,        /* Name of function */
    +            test       /* Argument(s) */
    +        );
    +    }
    +
         virtual void pure_virtual() {
             PYBIND11_OVERLOAD_PURE(
                 void,         /* Return type */

fails to compile with this error:

    make
    Scanning dependencies of target example
    [  7%] Building CXX object CMakeFiles/example.dir/example/example12.cpp.o
    pybind11/example/example12.cpp:30:18: warning: unused parameter ‘test’ [-Wunused-parameter]
         virtual void test(void *test)
                      ^
    In file included from pybind11/include/pybind11/attr.h:13:0,
                     from pybind11/include/pybind11/pybind11.h:32,
                     from pybind11/example/example.h:1,
                     from pybind11/example/example12.cpp:10:
    pybind11/include/pybind11/cast.h: In instantiation of ‘pybind11::object pybind11::handle::call(Args&& ...) const [with Args = void*&]’:
    pybind11/example/example12.cpp:57:9:   required from here
    pybind11/include/pybind11/cast.h:581:79: error: invalid conversion from ‘void*’ to ‘const pybind11::detail::void_type*’ [-fpermissive]
                 std::forward<Args>(args_), return_value_policy::reference, nullptr), false)... }
                                                                                   ^
    In file included from pybind11/include/pybind11/attr.h:13:0,
                     from pybind11/include/pybind11/pybind11.h:32,
                     from pybind11/example/example.h:1,
                     from pybind11/example/example12.cpp:10:
    pybind11/include/pybind11/cast.h:304:5: error:   initializing argument 1 of ‘static pybind11::handle pybind11::detail::type_caster<pybind11::detail::void_type>::cast(const pybind11::detail::void_type*, pybind11::return_value_policy, pybind11::handle)’ [-fpermissive]
         PYBIND11_TYPE_CASTER(void_type, _("NoneType"));
         ^
    make[2]: *** [CMakeFiles/example.dir/example/example12.cpp.o] Error 1
    make[1]: *** [CMakeFiles/example.dir/all] Error 2
    make: *** [all] Error 2

I'm not sure how to fix this. Should it be possible or is it simply not supported?

Thanks

**Comment by wjakob** [comment]
It's not supported. Pybind11 must know about the type -- void* is just a black box pointer, for which it doesn't know what to do.
