### ISSUE TITLE
Handling NULL pointer

### ISSUE THREAD

**Issue by sgranjoux** [wjakob/pybind11#107]
Hi,

I have a C++ object (CNode) having a member which is a pointer on another object(CRule) but it's allowed to have NULL here if the other object is not present. In Python, it corresponds to the other object or None.

To wrap this C++ object, I have defined set function accepting a pointer on such object, a get function and a property using def_property.

My problem is that when the Python code try to set this member to None, I get an error:
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (CNode, CRule) -> NoneType
Indeed None is not a CRule object. How to handle this situation?

I have seen that you can have several C++ functions for the same name. So I have try to redefine the property with another set function having no argument but it seems that it's not possible to overload property, only the last definition seems to be used.

Another option would be to allow none when requiring a pointer on an object but I suppose it needs a change in pybind11.

Do you have some ideas?

**Comment by wjakob** [comment]
That's weird, I think that should work. Can you upload a small self-contained example to facilitate debugging this?

**Comment by sgranjoux** [comment]
Thank you, that's a fast answer. What should work? overloading properties or allowing NULL in object pointers? Anyway, I will write a small example.

**Comment by wjakob** [comment]
(allowing null object pointers. Overloading properties doesn't make much sense to me)

**Comment by sgranjoux** [comment]
So here is my C++ code:
```c++
#include <pybind11/pybind11.h>

namespace py = pybind11;

class CNode
{
public:
        CNode(void) : mChild(NULL) {}

        CNode* GetChild(void) {return mChild;}
        void SetChild(CNode *child) {mChild = child;}
private:
        CNode* mChild;
};

PYBIND11_PLUGIN(tc) {
        py::module m("tc", "test null pointer");

        py::class_<CNode>(m, "Node")
                .def(py::init<>())
                .def_property("child", &CNode::GetChild, &CNode::SetChild);

        return m.ptr();
}
```

And the Python code
```python
import tc

if __name__ == "__main__":
        node = tc.Node()
        print("Set child")
        node.child = node
        print("Set no child")
        node.child = None
```

I get the following output
```
Set child
Set no child
Traceback (most recent call last):
  File "tc.py", line 11, in <module>
    node.child = None
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (CNode, CNode) -> NoneType
```

**Comment by wjakob** [comment]
Surprisingly this was indeed an issue in pybind11 which nobody (including me) noticed so far :). Fixed, thank you for the report.
