### ISSUE TITLE
Passing both python functions and std::function as arguments interchangeably

### ISSUE THREAD

**Issue by Vayu** [wjakob/pybind11#11]
I noticed that including `pybind11/functional.h` has some (probably) unintended side-effects.

If I include `pybind11/functional.h` I cannot pass `std::function` instances which I get from C++ code back to C++ functions. On the other hand without `pybind11/functional.h`, I cannot pass Python methods to C++ functions expecting `std::function`.

Is it possible to get both working, or are they mutually exclusive? I'm attaching a short example

```C++
#include <pybind11/pybind11.h>
#include <pybind11/functional.h>  // comment/uncomment this

struct Functor {
    bool operator() (int a, int b) const {
      return a < b;
    }
    std::function<bool(int, int)> cast() {
      return std::function<bool(int, int)>(*this);
    }
};

struct Caller {
    bool call(std::function<bool(int, int)> func, int a, int b) {
      return func(a, b);
    }
};

namespace py = pybind11;

PYBIND11_PLUGIN(tmp) {
    py::module m("tmp", "pybind11 tmp plugin");

    py::class_<Caller>(m, "Caller").def(py::init<>())
                                   .def("call", &Caller::call);

    py::class_<std::function<bool(int, int)>>(m, "FuncType").def(py::init<>());

    py::class_<Functor>(m, "Functor").def(py::init<>())
                                     .def("__call__", [](const Functor& f, int a, int b) { return f(a, b); })
                                     .def("cast", &Functor::cast);
    return m.ptr();
}
```

```Python
import tmp

cppfunc = tmp.Functor()
caller = tmp.Caller()

def pyfunc(a, b):
    return a < b

try:
    print 'Calling C++ functor {0!r}'.format(cppfunc),
    res = cppfunc(1, 2)
    print 'OK'
except Exception as error:
    print 'FAILED with error {1!r}'.format(cppfunc, error)

try:
    print 'Calling C++ with Python function {0!r}'.format(pyfunc),
    caller.call(pyfunc, 1, 2)
    print 'OK'
except Exception as error:
    print 'FAILED with error {1!r}'.format(cppfunc, error)

stdfunc = cppfunc.cast()
try:
    print 'Calling C++ with C++ function {0!r}'.format(stdfunc),
    caller.call(stdfunc, 1, 2)
    print 'OK'
except Exception as error:
    print 'FAILED with error {1!r}'.format(cppfunc, error)
```

Without `pybind11/functional.h`
```
Calling C++ functor <tmp.Functor object> OK
Calling C++ with Python function <function pyfunc> FAILED with error TypeError('Incompatible function arguments. The following argument types are supported:\n    1. (Caller, std::function<bool (int, int)>, int32_t, int32_t) -> bool\n',)
Calling C++ with C++ function <tmp.FuncType object> OK
```

With `pybind11/functional.h`
```
Calling C++ functor <tmp.Functor object> OK
Calling C++ with Python function <function pyfunc> OK
Calling C++ with C++ function <built-in method  of PyCapsule object> FAILED with error TypeError('Incompatible function arguments. The following argument types are supported:\n    1. (Caller, function<(int32_t, int32_t) -> bool>, int32_t, int32_t) -> bool\n',)
```

**Comment by wjakob** [comment]
Fixed in commit eb7c0b82ec21e1d63019f170fee3315d7058d9dd -- all cases now work when including functional.h. One thing you'll have to keep in mind though is that when passing functions back and forth is that each roundtrip will add one layer of Python -> C++ -> Python instrumentation that gets called every time you invoke the 2x wrapped function :). To avoid that, you will have to split your codebase into parts that include functional.h and those that don't.

**Comment by Vayu** [comment]
Thanks!

Perhaps that is worth adding to documentation, so people who want minimum overhead would stick to "non-functional" approach.

By splitting into parts, you mean separate classes at least? It doesn't look like same class could have both methods with "functional" semantics and "object" semantics.

**Comment by wjakob** [comment]
Ok, I added a warning.

You can actually do the aforementioned split, for instance by passing a pybind11::class_ to another translation unit (that doesn't include functional), which adds further functions.
