### ISSUE TITLE
overridden method returning bool in python always return true

### ISSUE THREAD

**Issue by jmabille** [wjakob/pybind11#110]
Assume we have a C++ interface with a pure virtual function returning a bool. If we use an alias class with trampoline methods as described [here](http://pybind11.readthedocs.org/en/latest/advanced.html#overriding-virtual-functions-in-python) and override the virtual function in a python class, the C++ code invoking the virtual function will always get a True value.

Here is a sample code to reproduce the issue:

```C++
class Base {
public:
    virtual ~Base() { }
    virtual bool run() = 0;
};

class PyBase : public Base {
public:
    using Base::Base;

    bool run() {
        PYBIND11_OVERLOAD_PURE(
            bool,
            Base,
            run,
        );
    }
};

bool call_run(Base *animal) {
    return animal->run();
}

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

    py::class_<PyBase>(m, "Base");
        .alias<Base>()
        .def(py::init<>())
        .def("run", &Base::run);

    m.def("call_run", &call_run);

    return m.ptr();
}
```
The Python session below shows how to reproduce the bug:
```python
>>> from example import *
>>> class Derived(Base):
...     def run(self):
...         return False
...
>>> d = Derived()
>>> print(call_run(d))
>>> True
```

**Comment by jmabille** [comment]
Looking at the header cast.h:

```C++
template <typename T> inline T cast(handle handle) {
    detail::type_caster<typename detail::intrinsic_type<T>::type> conv;
    if (!conv.load(handle, true))
        throw cast_error("Unable to cast Python object to C++ type");
    return conv;
}

template <typename T> inline object cast(const T &value, return_value_policy policy = return_value_policy::automatic, handle parent = handle()) {
    if (policy == return_value_policy::automatic)
        policy = std::is_pointer<T>::value ? return_value_policy::take_ownership : return_value_policy::copy;
    return object(detail::type_caster<typename detail::intrinsic_type<T>::type>::cast(value, policy, parent), false);
}
template <typename T> inline T handle::cast() const { return pybind11::cast<T>(m_ptr); }
```

The bug comes from the last line; when template parameter is bool, since m_ptr is a pointer, it will be silently converter to a bool and the wrong free cast overload will be called.

**Comment by wjakob** [comment]
ouch -- does it work when wrapping ``m_ptr`` in a ``handle()`` call?

**Comment by wjakob** [comment]
or maybe just ``*this`` instead of ``m_ptr``..

**Comment by jmabille** [comment]
Yes but this breaks other tests. I have a fix ready, I'm opening the PR.

**Comment by wjakob** [comment]
I just tried ``*this``, and it at least passes example1-13 tests on my end.

**Comment by jmabille** [comment]
Ok, I've only tested with handle(m_ptr). I will close the PR.

**Comment by wjakob** [comment]
thanks for tracking that down! I added the ``*this`` fix and cherry-picked your testcases from the PR.

**Comment by jmabille** [comment]
Thanks !
