### ISSUE TITLE
vector of unique_ptr

### ISSUE THREAD

**Issue by fkloosterman** [wjakob/pybind11#115]
Is it possible to wrap a class constructor that takes a std::vector<std::unique_ptr<MyClass>> argument? I have tried the following, but it results in compile errors related to the unique_ptr:

```
#include <vector>
#include <memory>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

class A {
public:
    A(int x=0): x_(x) {}
private:
    int x_;
};

class B {
public:
    B( std::vector<std::unique_ptr<A>> v ) {
        for (auto & a : v) {
            m_.push_back( std::move(a) );
        }
    }
private:
    std::vector<std::unique_ptr<A>> m_;
};

namespace py = pybind11;

PYBIND11_PLUGIN(test) {

    py::module m("test", "test module");
    
    py::class_<A>(m, "A")
        .def(py::init<int>());
    
    py::class_<B>(m, "B")
        .def(py::init<std::vector<std::unique_ptr<A>>>());
    
    return m.ptr();
    
}
```

**Comment by wjakob** [comment]
This kind of lifetime management directly in the function type is unfortunately beyond the scope of the library. Python would have to completely forget about some object that it's currently referencing and hand it over to the C++ side -- not sure that's even possible.

**Comment by Vladec** [comment]
So if I understand your answer correcly, that is not possible to bind a simpler code like this one :

```
class B {
public:
    B(  std::unique_ptr<A> v ):
       m_(std::move(v))
    {}

private:
   std::unique_ptr<A> m_;
};
```

?

By the way, I'm trying to expose a function that return a unique_ptr and I don't understand how 


```
class Example
{
public:
    class Value
    {
    public:
        Value(int x):_x(x)  {}
        int get_value() const { return _x; }
    protected:
        int _x;
    };

public:
    Example()
    { }

    std::unique_ptr<Value> create_value() { return std::make_unique<Value>(7); }
};

using Value = Example::Value;

PYBIND11_DECLARE_HOLDER_TYPE(Value, std::unique_ptr<Value>);

void init_ex1(py::module &m)
{
    py::class_<Example::Value>(m, "Value")
        .def(py::init<int>())
        .def("get_value", &Example::Value::get_value);

    py::class_<Example>(m, "Example")
            .def(py::init<>())
            .def("create_value", &Example::create_value);
}
```

This one will compile but always lead to a segmentation fault at runtime, the Value instance is destroyed before beeing forwarded to python layer.

**Comment by wjakob** [comment]
The contract of unique_ptr is that only one instance owns the object. You thus have to be extremely careful with call policies in that case so that ownership is correctly assigned, e.g. using the keep_alive policy or the reference_internal return value policy. Please see the documentation and example code for details -- this tracker is mainly intended for bug reports.

**Comment by wjakob** [comment]
An update on this:  the last commit (https://github.com/pybind/pybind11/commit/9f0dfce84b716b3e2a5e79be4fd6df5f09131626)
introduces the ability to return values via std::unique_ptr. The implied contract is that they will be owned by pybind11.

**Comment by Vladec** [comment]
Great!

Thanks a lot.
