### ISSUE TITLE
PYBIND11_DECLARE_HOLDER_TYPE small fix 

### ISSUE THREAD

**Issue by ivalylo** [wjakob/pybind11#12]
This is just a small one:

<code>template \<typename type\> class type_caster\<holder_type\></code>

should be 

<code>template <> class type_caster\<holder_type\></code>

Tested with VC2015

**Comment by wjakob** [comment]
I assume you refer to the line
```
template <typename type> class type_caster<holder_type>
```
This is intentional -- the type 'holder_type' is itself supposed to be a template that depends on type. Try changing to what you suggested -- you'll see that the included examples don't compile anymore.

**Comment by ivalylo** [comment]
Sorry, the markup messed my text. I fixed it now. I mean "typename type" should be removed, since it's a template specialization. VC gives:

"explicit specialization is using partial specialization syntax, use template \<\> instead"

**Comment by wjakob** [comment]
Can you actually write how you're calling PYBIND11_DECLARE_HOLDER_TYPE?
I suspect you're not using the convention discussed in the documentation.

If the holder_type is a template type (as it is supposed to be) there won't be an explicit partial specialization..

**Comment by ivalylo** [comment]
Yes, you are right, I misunderstood the help. I thought T was an example, but it's supposed to work  as a template. I use different holders for different types, so I list them explicitly by class. Thanks for clearing that out.
