### ISSUE TITLE
c++ function that modifies reference not reflected in python

### ISSUE THREAD

**Issue by mlund** [wjakob/pybind11#16]
Hi Jakob,
In C++ I have a class `Space` with public member `vector<PointParticle> p` and a non-class function  template,
~~~~
template<class Tspace>
   void cm2origo(Tspace::Tparticlevector &p) { /* modify p */ }
~~~~
Wrapping is done with,
~~~~
typedef Space<PointParticle> Tspace;

m.def("cm2origo",  &cm2origo<Tspace>);

py::class_<Tspace>(m, "Space")
  .def_readwrite("p", &Tspace::p)
  .def ... 
~~~~
In python I can read/write to `p` as one would expect. However, when calling the exposed `cm2origo` function, changes to `p` are not transferred back to python. Any suggestions how to sort this out?

**Comment by wjakob** [comment]
The STL auto-binding code in ``stl.h`` transparently converts a std::vector to a Python list, but it does not transfer back changes (this is intentional, it would be costly to have to do a full sweep over the vector after each function call to detect changes and re-synchronize).

You will have to create your own bindings for a custom std::vector that "stays" on the C++ side, and which can be accessed from Python using iterators and the slicing protocol. See example 6 of the included demo plugin.

**Comment by mlund** [comment]
Thanks. I'd rather not change the c++ side and tried to define my vector as:
~~~~
py::class_<Tspace::particlevector> _pvec(m, "particlevector");
 _pvec.def("__len__", &Tspace::particlevector::size);
~~~~
hoping that `Space.p` would be returned as python type `particlevector` but it's still `list`. Any way to override the automatic STL conversion other than removing the header which is otherwise needed? I understand the performance issue mentioned in your last post, but wonder if it's possible to copy only for the case where the list is passed as a non-const argument. It certainly seems more intuitive, safe.

**Comment by wjakob** [comment]
Can't you just avoid including ``<pybind11/stl.h>``? In that case, your custom type definition will have precedence.

**Comment by wjakob** [comment]
(other than that, your class definition looks good)

**Comment by mlund** [comment]
Sure, but then all stl return types need to be manually specialized to get pythonic behavior, right? The project is rather large so slightly more fine-grained control of the implicit stl conversion would probably be useful, perhaps as an option ala the return policies. Thanks / Mikael

**Comment by wjakob** [comment]
It's tricky due to do this since the type casting system relies on template partial overloads that can't just be turned off once they have been introduced. I'm all ears if you have an idea, but I hesitate to complicate the library for this use case.

**Comment by mlund** [comment]
I can surely imagine it's non-trivial; I'll post my solution/workaround here when done. Thanks / Mikael

**Comment by levinandrew** [comment]
@mlund were you able to find a solution to this issue?

**Comment by vagrawal-aptina** [comment]
hi, did you get the solution/workaround for this problem?
I am facing a very similar problem in my code.
Any help will be highly appreciated.
Thanks, Vishal
