### ISSUE TITLE
Tests fail on OSX 

### ISSUE THREAD

**Issue by mikh3x4** [wjakob/pybind11#17]
I'm quite new to C programming in general so I might be doing something wrong:

I downloaded the zip, and unzipped it and cded into the resulting dictionary.

Run the following commands: 
`cmake .`
`make -j 4`
`make test`

The first two completed what appears to be successfully (no mention of errors). But make test says 12 out of 12 test failed and gives the following error:
`Errors while running CTest`
`make: *** [test] Error 8`

I'm running OS X 10.11.1 and `$c++ --version` gives:
`Apple LLVM version 7.0.0 (clang-700.1.76)`
`Target: x86_64-apple-darwin15.0.0`
`Thread model: posix`

Additionally trying the example from the [docs](http://pybind11.readthedocs.org/en/latest/basics.html) gives a massive error:
```bash
$c++ -O3 -shared -std=c++11 -I ~/Desktop/pybind11-master/include `python-config --cflags --libs` example.cpp -o example.so
In file included from example.cpp:1:
In file included from /Users/mik/Desktop/pybind11-master/include/pybind11/pybind11.h:26:
In file included from /Users/mik/Desktop/pybind11-master/include/pybind11/cast.h:13:
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:294:14: error: call to constructor of 'pybind11::int_' is ambiguous
        int_ start(start_), stop(stop_), step(step_);
             ^     ~~~~~~
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:273:5: note: candidate constructor
    int_(int value) : object(PyLong_FromLong((long) value), false) { }
    ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:274:5: note: candidate constructor
    int_(size_t value) : object(PyLong_FromSize_t(value), false) { }
    ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:270:7: note: candidate is the implicit move constructor
class int_ : public object {
      ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:270:7: note: candidate is the implicit copy constructor
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:294:29: error: call to constructor of 'pybind11::int_' is ambiguous
        int_ start(start_), stop(stop_), step(step_);
                            ^    ~~~~~
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:273:5: note: candidate constructor
    int_(int value) : object(PyLong_FromLong((long) value), false) { }
    ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:274:5: note: candidate constructor
    int_(size_t value) : object(PyLong_FromSize_t(value), false) { }
    ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:270:7: note: candidate is the implicit move constructor
class int_ : public object {
      ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:270:7: note: candidate is the implicit copy constructor
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:294:42: error: call to constructor of 'pybind11::int_' is ambiguous
        int_ start(start_), stop(stop_), step(step_);
                                         ^    ~~~~~
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:273:5: note: candidate constructor
    int_(int value) : object(PyLong_FromLong((long) value), false) { }
    ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:274:5: note: candidate constructor
    int_(size_t value) : object(PyLong_FromSize_t(value), false) { }
    ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:270:7: note: candidate is the implicit move constructor
class int_ : public object {
      ^
/Users/mik/Desktop/pybind11-master/include/pybind11/pytypes.h:270:7: note: candidate is the implicit copy constructor
3 errors generated.```

**Comment by wjakob** [comment]
Hi,

can you please check if it works with the latest version?

Thanks,
Wenzel

**Comment by mikh3x4** [comment]
With the newest version (commit 7f8d1c2) `make test` still fails in the same way. The example compiles fine, and works as expected in python 2. Upon trying to import it to python 3 however it gives this error:
```python
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_example)```

Thank you for your help

**Comment by wjakob** [comment]
You need to make sure that Python picks up the right revisions of the Python binary and library (these are separate concepts in cmake, and unfortunately it sometimes get confused). It sounds like compilation was done with Python 2, while "make test" erroneously runs Python 3. A plugin can only be compiled for one specific Python version at a time.

**Comment by mikh3x4** [comment]
I looked in CMakeLists.txt but can't find an option to change the python version. I also tried compiling it with a python3 virtenv active, but it didn't work. Where would I be able to find the option to select the python version?

**Comment by wjakob** [comment]
You can use cmake-gui to change the PYTHON* variables and then rebuild. Alternative you can directly edit CmakeCache.txt

**Comment by mikh3x4** [comment]
I changed the following lines (187-ish and 343-ish) in CmakeCache.txt:
```bach
//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.5

//Path to a file.
PYTHON_INCLUDE_DIR:PATH=/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/include/python3.5m

//Path to a library.
PYTHON_LIBRARY:FILEPATH=/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/Python
```
and
```bash
FIND_PACKAGE_MESSAGE_DETAILS_PythonInterp:INTERNAL=[/usr/local/bin/python3.5][v3.5()]
//Details about finding PythonLibs
FIND_PACKAGE_MESSAGE_DETAILS_PythonLibs:INTERNAL=[/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/Python][/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/include/python3.5m][v3.5.0()]
//ADVANCED property for variable: PYTHON_EXECUTABLE
```
Then I rerun the 3 building/testing commands. All 12 test now pass successfully. The import to python 3 still fails. I'm using a brewed python3 if that makes a difference

**Comment by wjakob** [comment]
Hi -- that's good. 

However, all the tests do is to import the example library from the configured Python binary and run some tests. If these steps fails when you execute them manually, then something else is fishy -- maybe you're calling the wrong Python binary etc. Please double-check everything. I'm closing this ticket since the remainder does not seem to be a pybind11 issue.

Wenzel
