### ISSUE TITLE
Doesn't build with Clang on Linux

### ISSUE THREAD

**Issue by mrzv** [wjakob/pybind11#18]
`-flto` option prevents the example code from building on Linux with Clang (3.7). The problem is with the linker, it simply complains:
```
CMakeFiles/example.dir/example/example.cpp.o: file not recognized: File format not recognized
```
Removing `-flto` fixes everything. Apparently, this is not an unusual issue with Clang.

**Comment by wjakob** [comment]
Hi,

you need to use the 'gold' linker (http://llvm.org/docs/GoldPlugin.html) to use link time optimization with Clang. Maybe you are using plain LD? I prefer to have -flto in the build file by default as it leads to considerably smaller binaries. However, maybe support can be detected?

I can't reproduce this hear right now, so I am wondering if something like the following works for the CMakeLists.txt file? (in line 36)
```
  if (NOT ${U_CMAKE_BUILD_TYPE} MATCHES DEBUG)
    CHECK_CXX_COMPILER_FLAG("-flto" HAS_LTO_FLAG)
    if (HAS_LTO_FLAG)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden -flto")
    endif() 
  endif()
```

Thanks,
Wenzel

**Comment by wjakob** [comment]
Actually, this would be even better:
```
  # Enable link time optimization and set the default symbol
  # visibility to hidden (very important to obtain small binaries)
  if (HAS_LTO_FLAG AND NOT ${U_CMAKE_BUILD_TYPE} MATCHES DEBUG)
    # Default symbol visibility
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden")

    # Check for Link Time Optimization support
    CHECK_CXX_COMPILER_FLAG("-flto" HAS_LTO_FLAG)
    if (HAS_LTO_FLAG)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -flto")
    endif()
  endif()
```

Does that work for you?

**Comment by mrzv** [comment]
Yup, this works. Thanks.
