### ISSUE TITLE
Documentation about creating numpy arrays

### ISSUE THREAD

**Issue by polygon** [wjakob/pybind11#27]
A common use-case for my python extensions is to do some calculations that are difficult to vectorize using numpy. They usually accept some numpy arrays and will also return one but can't be simplified so that py::vectorize can be used. I've found that the documentation could use an example on how to do this. From reading the implementation of py::vectorize in numpy.h, I've managed to assemble the following:

```c++
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>

namespace py = pybind11;

py::array_t<double> add_arrays(py::array_t<double> i, py::array_t<double> j)
{
  py::buffer_info info_i = i.request();
  py::buffer_info info_j = j.request();
  
  if ((info_i.ndim != 1) || (info_j.ndim != 1))
    throw std::runtime_error("Number of dimensions must be one");
    
  if (info_i.shape[0] != info_j.shape[0])
    throw std::runtime_error("Input shapes must be equal");
    
  std::vector<double> ret(info_i.shape[0]);
  for (unsigned int idx = 0; idx < info_i.shape[0]; idx++)
    ret[idx] = ((double*)info_i.ptr)[idx] + ((double*)info_j.ptr)[idx];
    
  std::vector<size_t> strides = {sizeof(double)};
  std::vector<size_t> shape = {info_i.shape[0]};
  size_t ndim = 1;
  
  return py::array(py::buffer_info(ret.data(), sizeof(double),
                   py::format_descriptor<double>::value(),
                   ndim, info_i.shape, strides));
}                  


PYBIND11_PLUGIN(test)
{
  py::module m("test", "Testing pybind11 with numpy arrays");
  
  m.def("add_arrays", &add_arrays, "Adding two numpy arrays");
  
  return m.ptr();
} 
```

Furthermore I've found that for 1D-arrays, the return line could be further simplified to

```c++
  return py::array(info_i.shape[0], ret.data());
```

I wonder if this implementation is good or if things could be improved. If I understand correctly, during construction of the numpy array, the memory from the vector is copied. Is it possible to prevent that copy operation somehow?

However for the actual request I think this kind of code would be very interesting to people transitioning from Matlab to Python who want to have a replacement for their MEX extensions. This kind of task (non-vectorizable function on arrays with a returned array) is pretty common there and I spent quite some time figuring it out. While it taught me some interesting things, a good example might save other people from having to do that.

If the above code is good I can also provide a pull request for the docs based on it.

**Comment by wjakob** [comment]
Hi Polygon,

your example looks great!

You are right that the memory is copied during the construction of ``array``. The way to avoid this is by creating the array first and then writing the data directly to it--in retrospect I wonder why I didn't do that in ``vectorize()``... (it's been a while since I wrote this code)

If that also works, it might be good to change the implementation of vectorize to get that small extra performance boost.

In either case: getting a PR for a documentation update sounds great! Could you fix the code style to match the rest of the project in this case? (no extra line for opening braces, 4 spaces indent) 

Thanks,
Wenzel

**Comment by wjakob** [comment]
hey -- just checking in: are you still planning to submit a PR for the documentation update?

**Comment by polygon** [comment]
Hello, yes I'm still planning to do this. It was a bit busy over the holidays here.
