### ISSUE TITLE
Readme say BSD-style license; LICENSE is ZLib

### ISSUE THREAD

**Issue by Zac-HD** [wjakob/pybind11#28]
It's not entirely wrong, but calling it the Zlib license in the readme would be a lot clearer.

**Comment by wjakob** [comment]
ha, interesting! I must admit I just copied it from somewhere. So what's the difference between the BSD and zlib licenses? I googled but can't find anything conclusive. (I'm trying to decide whether to just fix the documentation or change the LICENSE.txt file)

**Comment by mrzv** [comment]
https://tldrlegal.com/license/zlib-libpng-license-(zlib)
https://tldrlegal.com/license/bsd-3-clause-license-(revised)

**Comment by wjakob** [comment]
ok, awesome -- I like that website :).

I switched to BSD 3-clause.

**Comment by mrzv** [comment]
One small suggestion. My employer uses a BSD 3-clause license, but they add an extra paragraph at the end to simplify dealing with contributions. For example: https://github.com/diatomic/diy2/blob/master/LICENSE.txt
I'm referring to the very last paragraph (about "Enhancements").

**Comment by wjakob** [comment]
That is an excellent idea -- done, thanks!
