### ISSUE TITLE
Lubuntu 15.04 Example Build Failures

### ISSUE THREAD

**Issue by Suudy** [wjakob/pybind11#3]
I cannot compile the examples out of the latest commit (ad7bc01d516c39829238a4a2b4db7d8f8a30a8f9) on my Lubuntu 15.04 machine.

$ gcc --version
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2

And the build log:

$ cmake .
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Setting build type to 'MinSizeRel' as none was specified.
-- Found PythonLibs: /usr/lib/i386-linux-gnu/libpython2.7.so (found version "2.7.9") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.9") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pladow/pybind11
$ make -j 4
Scanning dependencies of target example
[  7%] [ 15%] [ 23%] [ 30%] Building CXX object CMakeFiles/example.dir/example/example2.cpp.o
Building CXX object CMakeFiles/example.dir/example/example3.cpp.o
Building CXX object CMakeFiles/example.dir/example/example.cpp.o
Building CXX object CMakeFiles/example.dir/example/example1.cpp.o
In file included from /home/pladow/pybind11/include/pybind11/cast.h:13:0,
                 from /home/pladow/pybind11/include/pybind11/pybind11.h:26,
                 from /home/pladow/pybind11/example/example.h:1,
                 from /home/pladow/pybind11/example/example3.cpp:10:
/home/pladow/pybind11/include/pybind11/pytypes.h:254:5: error: ‘pybind11::int_::int_(pybind11::ssize_t)’ cannot be overloaded
     int_(ssize_t value) : object(PyLong_FromSsize_t(value), false) { }
     ^
In file included from /home/pladow/pybind11/include/pybind11/cast.h:13:0,
                 from /home/pladow/pybind11/include/pybind11/pybind11.h:26,
                 from /home/pladow/pybind11/example/example.h:1,
                 from /home/pladow/pybind11/example/example1.cpp:11:
/home/pladow/pybind11/include/pybind11/pytypes.h:254:5: error: ‘pybind11::int_::int_(pybind11::ssize_t)’ cannot be overloaded
     int_(ssize_t value) : object(PyLong_FromSsize_t(value), false) { }
     ^
/home/pladow/pybind11/include/pybind11/pytypes.h:251:5: error: with ‘pybind11::int_::int_(int)’
     int_(int value) : object(PyLong_FromLong((long) value), false) { }
     ^
/home/pladow/pybind11/include/pybind11/pytypes.h:251:5: error: with ‘pybind11::int_::int_(int)’
     int_(int value) : object(PyLong_FromLong((long) value), false) { }
     ^
In file included from /home/pladow/pybind11/include/pybind11/cast.h:13:0,
                 from /home/pladow/pybind11/include/pybind11/pybind11.h:26,
                 from /home/pladow/pybind11/example/example.h:1,
                 from /home/pladow/pybind11/example/example.cpp:10:
/home/pladow/pybind11/include/pybind11/pytypes.h:254:5: error: ‘pybind11::int_::int_(pybind11::ssize_t)’ cannot be overloaded
     int_(ssize_t value) : object(PyLong_FromSsize_t(value), false) { }
     ^
/home/pladow/pybind11/include/pybind11/pytypes.h:251:5: error: with ‘pybind11::int_::int_(int)’
     int_(int value) : object(PyLong_FromLong((long) value), false) { }
     ^
In file included from /home/pladow/pybind11/include/pybind11/cast.h:13:0,
                 from /home/pladow/pybind11/include/pybind11/pybind11.h:26,
                 from /home/pladow/pybind11/example/example.h:1,
                 from /home/pladow/pybind11/example/example2.cpp:11:
/home/pladow/pybind11/include/pybind11/pytypes.h:254:5: error: ‘pybind11::int_::int_(pybind11::ssize_t)’ cannot be overloaded
     int_(ssize_t value) : object(PyLong_FromSsize_t(value), false) { }
     ^
/home/pladow/pybind11/include/pybind11/pytypes.h:251:5: error: with ‘pybind11::int_::int_(int)’
     int_(int value) : object(PyLong_FromLong((long) value), false) { }
     ^
CMakeFiles/example.dir/build.make:54: recipe for target 'CMakeFiles/example.dir/example/example.cpp.o' failed
make[2]: *** [CMakeFiles/example.dir/example/example.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/example.dir/build.make:123: recipe for target 'CMakeFiles/example.dir/example/example3.cpp.o' failed
make[2]: *** [CMakeFiles/example.dir/example/example3.cpp.o] Error 1
CMakeFiles/example.dir/build.make:77: recipe for target 'CMakeFiles/example.dir/example/example1.cpp.o' failed
make[2]: *** [CMakeFiles/example.dir/example/example1.cpp.o] Error 1
CMakeFiles/example.dir/build.make:100: recipe for target 'CMakeFiles/example.dir/example/example2.cpp.o' failed
make[2]: *** [CMakeFiles/example.dir/example/example2.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/example.dir/all' failed
make[1]: *** [CMakeFiles/example.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wjakob** [comment]
Hello Suudy,

I committed a fix, can you confirm that it works for you?

Best,
Wenzel

**Comment by Suudy** [comment]
That did it!

Thanks for the fix.
