### ISSUE TITLE
Efficiency question

### ISSUE THREAD

**Issue by hlzz** [wjakob/pybind11#33]
I just have this maybe sort of silly question. For what I understand this library can help us create python wrapper of c++ code easily, right? So the compiled module for python, converted from c++, will be really efficient, since the functioning part of the code is actually written by c++. Is my understanding correct? Thanks.

**Comment by wjakob** [comment]
That's right -- the C++ part will be as fast as usual, so the key is to write just the few expensive operations in C++. That way, you can have the convenience of Python scripting with essentially native performance.
