### ISSUE TITLE
Const correctness

### ISSUE THREAD

**Issue by adler-j** [wjakob/pybind11#35]
When trying to move from boost::python to pybind11 (I really love this initiative), i learned that pybind11 does not seem to be properly const-correct. This causes issues, for example, one would expect this to work:

```cpp
void my_fun(const py::array& arr) {
    size_t size = arr.request().count
}
```

It fails because request is not declared `const`. The same applies to *many* other functions.

**Comment by wjakob** [comment]
Agreed, this is something I did not pay much attention to. It might be a lot of work to change everything though -- I'll mark it as a possible improvement for v2.x but must admit that I don't have enough free cycles to take it on right now myself.

**Comment by tmiasko** [comment]
I also hit this issue a few times already. It is not a significant problem, but
still a little bit inconvenient. 

I would like to make those wrappers around python object to have the same
semantics with respect to constness as pointers. For example, given an instance
of const pybind11::dict, it wouldn't be possible to change pointer referring to
the python dictionary but it would be possible to change the pointee, e.g.,
insert new items to the dictionary through this handle.

If this is fine with you, I can provide patch for types from pytypes.h.

**Comment by wjakob** [comment]
Yes, please go ahead -- I would welcome such a patch. It would be great if you could make a consistent change of all of the structures in ``pytypes.h``.

**Comment by wjakob** [comment]
Closing this ticket, as the PR was merged.
