### ISSUE TITLE
array.API and numpy headers

### ISSUE THREAD

**Issue by adler-j** [wjakob/pybind11#36]
In `array.API`, several (but not all) numpy macros are declared as functions, this is all fine, but it causes issues when you import numpy before pybind11.

For example

```cpp
#include <numpy/arrayobject.h>
#include <pybind11/pybind11.h>
```

causes compilation crashes because the macros (defined in numpy) interfere with the names defined in pybind11.

**Comment by wjakob** [comment]
Aha, interesting -- yes, it was never intended that arrayobject.h is included at the same time. Again, if you can separate these to avoid the namespace clash then that would be appreciated.
