### ISSUE TITLE
Exception conversion

### ISSUE THREAD

**Issue by adler-j** [wjakob/pybind11#37]
Boost::python supports, and it would be nice if pybind11 did aswell, conversion of errors. I have legacy code which contains this snippet

```cpp
if (index < 0 || index >= size())
    throw std::out_of_range("index out of range");
```

in boost python, this was converted to `IndexError` in python. This allows my container to be used with python expressions such as `list(my_object)` since this is implemented something like this in python

```python
def list(obj):
    result = []
    i = 0
    while True:
        try:
            result += [obj[i]]
            i += 1
        except IndexError:
            break
```

But with pybind11, it becomes a `RunTimeError` and all such logic fails.

**Comment by wjakob** [comment]
sounds good to me -- do you want to submit a PR? The place to patch will be the dipatch function in pybind11.h.

**Comment by adler-j** [comment]
Sure I can submit a PR, but i get

```
remote: Permission to wjakob/pybind11.git denied to adler-j.
fatal: unable to access 'https://github.com/wjakob/pybind11/': The requested URL
 returned error: 403
``` 

I guess you need to allow users to push (perhaps not to master).

**Comment by wjakob** [comment]
The github "model" is that you can't directly commit to someone else's repository by default. The approach is to clone the repository to your personal page, make changes, and then submit a PR.

**Comment by adler-j** [comment]
Oh ofc, realized that, will do.

**Comment by wjakob** [comment]
awesome, committed -- thanks!

**Comment by wjakob** [comment]
oops, never mind -- that was another PR I merged :).

**Comment by adler-j** [comment]
Seems your build server has some issues, will get em fixed.

**Comment by wjakob** [comment]
committed now!
