### ISSUE TITLE
Accessing underlying C++ object from generic python object

### ISSUE THREAD

**Issue by jtravs** [wjakob/pybind11#39]
I expect this is a trivial question, and apologies for that, but I cannot work out how to do this.

If I have exposed a C++ type to python using pybind11 and created several instances of it in python, stored in a list, what is the best way to obtain these instances in a different C++ function (jn this case the constructor of another class). I tried passing the list directly to a function expecting  a ```std::vector<MyType>``` but this does not work. i.e.
```C++
py::class_<AnotherType>(m, "AnotherType")
    .def("__init__",
             [](AnotherType &instance, std::vector<MyType> instances) {
    ...
    }
```
I also wrote a lambda function in C++ to accept a ```py::list``` object; that worked, but I do not know how to extract the C++ types from the py::objects inside the list.
```C++
py::class_<AnotherType>(m, "AnotherType")
     .def("__init__",
             [](AnotherType &instance, py::list instances) {
                 for (auto inst : instances) {
                    //what do I do here?
                 }
    ...
    }
```

What I actually want in the end is a ```std::vector<std::shared_ptr<MyType>>```.

What is the best way to achieve this?

**Comment by wjakob** [comment]
IMHO the first approach is the way to go and should work. Can you clarify why it didn't? Things to check will be whether ``stl.h`` is included, and whether you registered ``shared_ptr`` as discussed in the advanced section of the documentation.

Also, to make assistance easier from my end easier, please provide a self-contained minimal example if none of the above helped.

**Comment by jtravs** [comment]
Thanks for your quick answer! I will investigate further and make a minimal example as I would also prefer that way. I found the alternative solution by using ```MyClass *cls = obj.cast<MyClass *>();``` after reading the docs more carefully.

**Comment by jtravs** [comment]
OK, so I made a minimal example and the version you suggest works:
```C++
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <vector>
#include <memory>

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

struct MyType {
    int i_;
    MyType(int i) : i_(i) {};
};


struct AnotherType {
    std::vector<MyType> types_;
    AnotherType(std::vector<MyType> types) : types_(types) {};
};


PYBIND11_PLUGIN(vtest2) {
    py::module m("vtest2", "vector test plugin");

    py::class_<MyType>(m, "MyType")
        .def(py::init<int>());

    py::class_<AnotherType>(m, "AnotherType")
        .def("__init__",
             [](AnotherType &instance,
                std::vector<MyType> types) {
                    new (&instance) AnotherType(types); });

    return m.ptr();
}
```

But if I try it with shared pointers:
```C++
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <vector>
#include <memory>

namespace py = pybind11;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

struct MyType {
    int i_;
    MyType(int i) : i_(i) {};
};


struct AnotherType {
    std::vector<std::shared_ptr<MyType>> types_;
    AnotherType(std::vector<std::shared_ptr<MyType>> types) : types_(types) {};
};


PYBIND11_PLUGIN(vtest) {
    py::module m("vtest", "vector test plugin");

    py::class_<MyType>(m, "MyType")
        .def(py::init<int>());

    py::class_<AnotherType>(m, "AnotherType")
        .def("__init__",
             [](AnotherType &instance,
                std::vector<std::shared_ptr<MyType>> types) {
                    new (&instance) AnotherType(types); });

    return m.ptr();
}
```
I get the error:
```
error: 'struct MyType' has no member named 'shared_from_this'
         holder = holder_type(((type *) parent::value)->shared_from_this());
```

While I can add this method, I';d rather not change my C++ code. Is there a way around this? Basically, I want to avoid copying all of the MyTypes and instead use share_ptr to manage one instance.

**Comment by wjakob** [comment]
Your object *needs* to extend ``enable_shared_from_this`` (http://en.cppreference.com/w/cpp/memory/enable_shared_from_this) if you want to use shared pointers. This is an absolute must, otherwise it's impossible to keep reference counts consistent between Python and C++. See also the warning boxes in the docs.

**Comment by jtravs** [comment]
OK, fair enough, I'll add that (thanks for educating me!). With that change I get this error:
```Python
In [1]: import vtest

In [2]: mt1 = vtest.MyType(1)

In [3]: mt2 = vtest.MyType(2)

In [4]: at = vtest.AnotherType([mt1,mt2])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-7fed78ff0170> in <module>()
----> 1 at = vtest.AnotherType([mt1,mt2])

RuntimeError: bad_weak_ptr

```

**Comment by wjakob** [comment]
ha, interesting!

**Comment by wjakob** [comment]
The issue is that you have to declare the holder type as well:

```
     py::class_<MyType, std::shared_ptr<MyType>>(m, "MyType")
```

**Comment by jtravs** [comment]
Thanks. Sorry for the noise. I'll re-read the docs more carefully!
