### ISSUE TITLE
Conversion across modules

### ISSUE THREAD

**Issue by mrzv** [wjakob/pybind11#4]
The following works on Mac OS X, but not on Linux. (The obvious bits below, declarations of `m` and such, are ommited.)

```
// common.h

struct A {};
```

```
// a.cpp

#include "common.h"

PYBIND11_PLUGIN(a)
{
  py::class_<A>(m, "A")
      .def(py::init<>());
}
```

```
// b.cpp

#include "common.h"

PYBIND11_PLUGIN(b)
{
  m.def("test", [](A a) { fmt::print("test\n"); });
}
```

```
# test.py 

import a
import b

x = a.A()
b.test(x)
```

On Mac, this works fine. On Linux, I get:
```
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (A) -> None
```

**Comment by wjakob** [comment]
Hi Dmitriy,

it's a consequence of typeid(A) in a.cpp giving a different answer than in b.cpp. It would probably not have happened if "A" was defined in some shared libraries that both a.cpp and b.cpp link against.

That said, I have committed a simple workaround that should allow this case to work nonetheless. Can you verify that it works on your end?

-Wenzel

**Comment by mrzv** [comment]
Yup, that fixed it. Thanks.

**Comment by wjakob** [comment]
great, thanks.
