### ISSUE TITLE
Compilation error when trying to use sets

### ISSUE THREAD

**Issue by bennybp** [wjakob/pybind11#42]
When trying to convert set types, I get a compilation error:

    pybind11/include/pybind11/stl.h:87:37: error: invalid conversion from ‘long int’ to ‘PyObject* {aka _object*}’ [-fpermissive]

The source seems to be these lines (starting at line 87):

    if (PySet_Add(set, value) != 0) {
        Py_DECREF(value);
        Py_DECREF(set);
        return nullptr;

I think `value` on lines 87 and 88 should be `value_`, which is the PyObject * created on line 82:

    PyObject *value_ = value_conv::cast(value, policy, parent);

**Comment by wjakob** [comment]
Good catch, thanks! There was also an issue with reference counting for std::set, which I fixed.

**Comment by bennybp** [comment]
I'll piggyback on this issue since this is similar. Another compilation error is happening after your recent updates. Argument to `add()` at stl.h:80 is missing the underscore

    object value_ = object(key_conv::cast(value, policy, parent), false);
    if (!value_ || !s.add(value))
        return handle();

**Comment by wjakob** [comment]
wow, that is really embarrassing. I can't seem to get this file right, ever ;) What is even more surprising is that it compiles on my machine, the CI bots, and passes all tests everywhere! Hopefully it's all fixed now, and I will try to be more careful about ``stl.h``..
