### ISSUE TITLE
Compilation error test case - arch linux

### ISSUE THREAD

**Issue by mathben** [wjakob/pybind11#47]
I clone master of pybind11
> cmake .
> make -j8

I got errors
http://pastebin.com/TrXpEwqL

gcc version 5.3.0 (GCC)
python 3.5m

What information do you need?
Thank

**Comment by wjakob** [comment]
Cannot reproduce with GCC 5.3.0 (official toolchain PPA from https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa). I suspect there is something wrong with your compiler setup.

**Comment by mathben** [comment]
Arch linux have different active flag with gcc than another distribution like ubuntu, but the problem not seems to be gcc.
I can help you to diagnostic this bug if you want, because I am sure I am not alone with this problem.

**Comment by ddemidov** [comment]
I can not reproduce this on Arch linux either.
