### ISSUE TITLE
How to write c++ function that can consume python3 `bytes`?

### ISSUE THREAD

**Issue by kvikas** [wjakob/pybind11#49]
Hello,

This is not necessarily an issue, but a question. Sorry to ask here. I couldn't find an appropriate forum to ask questions about pybind11.

I've a python3 program and I want to rewrite some of the functionality in C++. The function I want to rewrite takes `bytes` as input. What would be the correct signature for corresponding C++ function? I'm trying to use pybind11 for the binding.

Thanks.

**Comment by wjakob** [comment]
It's currently not supported -- see PR #48.
