### ISSUE TITLE
Function overloading does not seems to work when keyword argument is used

### ISSUE THREAD

**Issue by lyskov** [wjakob/pybind11#54]
Hi @wjakob,

I noticed that function overloading does not seems to work when keyword argument is used (or works in rather confusing way). Supplying at least one keyword argument (even when no default values is specified) lead to wrong function resolution. Pybind version used: somewhat latest from GitHub (1546b85797e158c225f7ea163db39a61333a4d7f).

Is this behavior expected? Or something wrong with my code?

Thanks,

Code to replicate this:
```C++
#include <pybind11/pybind11.h>
#include <string>

std::string foo(int a) { return "foo1"; }
std::string foo(int a, int b) { return "foo2"; }
std::string foo(int a, int b, int c) { return "foo3"; }

PYBIND11_PLUGIN(example) {
	pybind11::module m("example", "example module");

	m.def("foo", (std::string (*)(int) ) &foo, "doc", pybind11::arg("a"));
	m.def("foo", (std::string (*)(int, int) ) &foo, "doc", pybind11::arg("a"), pybind11::arg("b"));
	m.def("foo", (std::string (*)(int, int, int) ) &foo, "doc", pybind11::arg("a"), pybind11::arg("b"), pybind11::arg("c"));

	return m.ptr();
}
```

Output:
```
In [1]: foo(1)
Out[1]: u'foo1'

In [2]: foo(1,2)
Out[2]: u'foo2'

In [3]: foo(1,2,3)
Out[3]: u'foo3'

In [4]: foo(a=1,b=2)
Out[4]: u'foo1'

In [5]: foo(a=1,b=2,c=3)
Out[5]: u'foo1'
```

**Comment by wjakob** [comment]
pybind11 will try overloads in the order that was specified until one of them works. If you declare them in the opposite order, it should work as expected.

**Comment by wjakob** [comment]
(it would be possible to make this more robust by validating that all keyword arguments are "consumed", but at an additional cost, but this would require modifications of the library)

**Comment by lyskov** [comment]
Thank you for info @wjakob ! Indeed reversion the order of definition fixed this. 

How costly it will be to validate that all keyword argument is consumed? Would it be possible to trigger addition of such validation by special C++ `#define` that could be defined at command line level?

My concern is that in current form it might be difficult for Python user to recognize such errors etc.

Thanks,

**Comment by wjakob** [comment]
see 3367cecc6b6d1641fad85c1684b15094445c228f

**Comment by lyskov** [comment]
Awesome!!! - thank you!
