### ISSUE TITLE
example.so not properly loaded with current branch

### ISSUE THREAD

**Issue by jkhoogland** [wjakob/pybind11#58]
Hi,
tried to build on OSX Yosemite, 
but it seems something is wrong, example.so doesn't load properly on OSX

```
__Py_ZeroStruct
```

is not properly exported...
I'll have a look to see if I can figure out what is going on, 
but if anybody has some idea what could be the issue much appreciated...

```
2016.01.02:19.42][Jiri@JiriMBP:~/lib/cpp/python/pybind11.orig/example]$  python
Python 3.4.3 |Anaconda 2.4.1 (x86_64)| (default, Oct 20 2015, 14:27:51)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/Jiri/Documents/lib/cpp/python/pybind11.orig/example/example.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /Users/Jiri/Documents/lib/cpp/python/pybind11.orig/example/example.so
  Expected in: flat namespace
 in /Users/Jiri/Documents/lib/cpp/python/pybind11.orig/example/example.so
>>>
```

System:
```
Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin
```

**Comment by wjakob** [comment]
You have to use the same version of Python for compilation and at runtime -- inspect the cmake settings.

**Comment by jkhoogland** [comment]
Hi

I added proper code to handle usage of Anaconda python
https://github.com/jkhoogland/pybind11/commit/f53ae24814d58958ff71b11892c78d27b0d008ed
Current CMake FindPythonLibs doesn't handle this properly (yet).

To have this switched on, set the option PYBIND11_ANACONDA when running ccmake

Let me know if you want to have this in your code,
then I will create a pull request.

It might be useful for everybody using Anaconda these days...

Cheers
Jiri

**Comment by ivan-krukov** [comment]
Can please make this a full pull request? Alternatively, this (https://github.com/pybind/pybind11/pull/118) is a viable solution.
Thanks!
