### ISSUE TITLE
use std::decay

### ISSUE THREAD

**Issue by adler-j** [wjakob/pybind11#59]
Currently we implement [decay here](https://github.com/wjakob/pybind11/blob/dd57a34e2d653478bf0b6f3d54c7c0cae46f3364/include/pybind11/common.h#L189-L195), but too me, we should be able to use [std::decay](http://en.cppreference.com/w/cpp/types/decay). Any reason we don't?

**Comment by wjakob** [comment]
Our decay decays more things -- std::decay doesn't do the following:
```
template <typename T, size_t N> struct decay<const T[N]> { typedef typename decay<T>::type type; };
template <typename T, size_t N> struct decay<T[N]>       { typedef typename decay<T>::type type; };
```

**Comment by adler-j** [comment]
Somewhat miss-leading naming then perhaps, how about a rename to something like `raw_type`?
