### ISSUE TITLE
Using pybind11 from pypi - directory with headers.

### ISSUE THREAD

**Issue by tmiasko** [wjakob/pybind11#60]
When using pybind11 from pypi what would be the best way  to determine the
directory with include files, in a manner that would work regardless if
pybind11 have been installed system wide, using user scheme, virtualenv, etc?
Maybe you have some suggestion given that pybind11 is distributed on pypi.

I will note, that I like how numpy installation scheme works, which just places
headers along with the python module, making it easy to locate from python:

    import numpy.core as core
    d = os.path.join(os.path.dirname(core.__file__), 'include')

Though it looks quite differently in pybind11 package (ignoring the fact the
pybind11, doesn't provide any python module).

**Comment by wjakob** [comment]
For me, the pypi install option puts the header files into the include directory of the underlying Python install — is that different for you? I’m not quite sure what to respond to this ticket.

**Comment by tmiasko** [comment]
As far as I was testing this, regardless of method I use to install pybind11,
directory with pybind11 is never on include path by default (when building the
Python extension). The question is then how to determine pybind11 location in
portable way so that it can be provided to setuptools.Extension.include_dirs.

Though, I found it more convenient to just include pybind11 in source package,
instead of specifying it as a requirement and downloading from pip, so feel
free to just close this issue.

**Comment by wjakob** [comment]
ok, will do. I usually add it as a git submodule.
