### ISSUE TITLE
pybind11 equivalent of boost with_custodian_and_ward

### ISSUE THREAD

**Issue by benEnsta** [wjakob/pybind11#62]
I am trying to use pybind11 instead of boost python and I didn't found the way may to set the correct call policies for my function call. (Maybe I missed something in the doc)

I have an object which takes in its constructor, a list  as argument and the lifetime of the list and the object need to be tied. In boost I need to use  *with_custodian_and_ward* call policy. 

What is the equivalent in pybind11 ?

**Comment by wjakob** [comment]
unfortunately, this is currently not yet supported.

**Comment by benEnsta** [comment]
Thank you. 
If I have time, I will try to work on that.  Do you have any idea to implement this ?

**Comment by DerThorsten** [comment]
I am willing to help here,
I would love to switch from boost::python to this lib but i also need 
with_custodian_and_ward and with_custodian_and_ward_postcall

**Comment by DerThorsten** [comment]
the boost header itself does not look to complicated
http://www.boost.org/doc/libs/1_48_0/boost/python/with_custodian_and_ward.hpp

**Comment by wjakob** [comment]
I plan to add this feature in a bit, stay tuned (currently busy with a deadline).

**Comment by DerThorsten** [comment]
Very nice =)
Is there a way to contribute???
I have humongous(!) experience with boost python and just features / tricks of boost python
where others do not even know they exist.
Like custom constructors with "with_custodian_and_ward". Try to do that  in Bp ;) ( hint: operator[..policies here])

**Comment by wjakob** [comment]
Hi Thorsten,
well, the goal is for this library to be nice and easy to use, so hopefully there is no need for any "tricks",as you say ;). At this point I think it's relatively feature-complete, but PRs are welcomed if there is a useful enhancement. The goal remains for everything to be super-compact, and my favorite kind of change is the one that replaces a complex implementation with a tiny one that does the same thing.
Cheers,
Wenzel
