### ISSUE TITLE
Unary Operators Compilation Failure

### ISSUE THREAD

**Issue by Suudy** [wjakob/pybind11#7]
I'm getting a compilation error when using a unary operator.  Here's some sample code that exhibits the problem.

This is on Lubuntu 15.04 with gcc 4.9.2.  Also on Kubuntu 14.04 with gcc 4.8.4.

```
#include <pybind11/pybind11.h>
#include <pybind11/operators.h>

namespace py = pybind11;

class foo
{
  public:
    foo(int f_) : m_f(f_)
    {
    }

    foo operator~() const
    {
      return foo(~m_f);
    }

  private:
    int m_f;
};

PYBIND11_PLUGIN(foo)
{
  py::module m("foom", "foom example");

  py::class_<foo>(m, "foo")
    .def(py::init<int>())

    .def(~py::self);

  return m.ptr();
}
```

I get the following errors:

In file included from test.cpp:2:0:
./pybind11/operators.h: In instantiation of ‘struct pybind11::detail::op_impl<(pybind11::detail::op_id)15, (pybind11::detail::op_type)2, foo, foo, pybind11::detail::undefined_t>’:
./pybind11/operators.h:52:29:   required from ‘void pybind11::detail::op_<id, ot, L, R>::execute(pybind11::class_<Base, Holder>&, Extra&& ...) const [with Base = foo; Holder = std::unique_ptr<foo, std::default_delete<foo> >; Extra = {}; pybind11::detail::op_id id = (pybind11::detail::op_id)15; pybind11::detail::op_type ot = (pybind11::detail::op_type)2; L = pybind11::detail::self_t; R = pybind11::detail::undefined_t]’
./pybind11/pybind11.h:703:9:   required from ‘pybind11::class_<type, holder_type>& pybind11::class_<type, holder_type>::def(const pybind11::detail::op_<id, ot, L, R>&, Extra&& ...) [with pybind11::detail::op_id id = (pybind11::detail::op_id)15; pybind11::detail::op_type ot = (pybind11::detail::op_type)2; L = pybind11::detail::self_t; R = pybind11::detail::undefined_t; Extra = {}; type = foo; holder_type = std::unique_ptr<foo, std::default_delete<foo> >]’
test.cpp:29:19:   required from here
./pybind11/operators.h:96:17: error: ‘l’ was not declared in this scope
     static auto execute(const L &l) -> decltype(expr) { return expr; }                 \
                 ^
./pybind11/operators.h:137:1: note: in expansion of macro ‘PYBIND11_UNARY_OPERATOR’
 PYBIND11_UNARY_OPERATOR(invert,     operator~,    ~l)
 ^
./pybind11/operators.h: In instantiation of ‘void pybind11::detail::op_<id, ot, L, R>::execute(pybind11::class_<Base, Holder>&, Extra&& ...) const [with Base = foo; Holder = std::unique_ptr<foo, std::default_delete<foo> >; Extra = {}; pybind11::detail::op_id id = (pybind11::detail::op_id)15; pybind11::detail::op_type ot = (pybind11::detail::op_type)2; L = pybind11::detail::self_t; R = pybind11::detail::undefined_t]’:
./pybind11/pybind11.h:703:9:   required from ‘pybind11::class_<type, holder_type>& pybind11::class_<type, holder_type>::def(const pybind11::detail::op_<id, ot, L, R>&, Extra&& ...) [with pybind11::detail::op_id id = (pybind11::detail::op_id)15; pybind11::detail::op_type ot = (pybind11::detail::op_type)2; L = pybind11::detail::self_t; R = pybind11::detail::undefined_t; Extra = {}; type = foo; holder_type = std::unique_ptr<foo, std::default_delete<foo> >]’
test.cpp:29:19:   required from here
./pybind11/operators.h:52:32: error: ‘execute’ is not a member of ‘op {aka pybind11::detail::op_impl<(pybind11::detail::op_id)15, (pybind11::detail::op_type)2, foo, foo, pybind11::detail::undefined_t>}’
         class_.def(op::name(), &op::execute, std::forward<Extra>(extra)...);
                                ^

**Comment by Suudy** [comment]
I also tested it on Lubuntu 15.10 with gcc 5.2.1.  Same error message.

**Comment by wjakob** [comment]
I pushed a fix -- can you please verify that it works now?

**Comment by Suudy** [comment]
That did fix it.  Strange though.  Looking at the preprocessed output before and after, they are essentially the same.  I'm not sure if it is complaining about the decltype(~l) or the 'return ~l;'.  It seems to me to be unambiguous in either case.

**Comment by Suudy** [comment]
And I just tested the build with Visual Studio 2015 and it does compile cleanly there (with the fa1bfb2 commit).

**Comment by wjakob** [comment]
Ok, good. I'm closing the ticket.
