### ISSUE TITLE
numpy.h indirectly defines `I` - breaks following includes

### ISSUE THREAD

**Issue by aherrmann** [wjakob/pybind11#75]
The header `pybind11/numpy.h` includes `complex.h` which, at least in glibc, defines `I` as a preprocessor macro to denote the imaginary unit. Unfortunately `I` is a popular name for template parameters in e.g. the boost library. Therefore, the following two lines will fail to compile

```
#include <pybind11/numpy.h>
#include <boost/variant.hpp>
```

while the following three lines will work fine.

```
#include <pybind11/numpy.h>
#undef I
#include <boost/variant.hpp>
```

The compiler error is very long, however it starts with

```
include/boost/move/iterator.hpp:151:11: error: declaration of anonymous class must be a definition
template <class I>
```

which indicates that the `I` is the problem.

It took me some time to find the cause for that particular error. Do you think it would be reasonable to `#undef I` within `pybind11/numpy.h` to spare others from the same problem?

**Comment by wjakob** [comment]
Hi -- the place to add the change will be pybind11/complex.h I think. (and with an appropriate ``#ifdef I`` test) -- feel free to submit a PR.

**Comment by ax3l** [comment]
fix added in #78

**Comment by aherrmann** [comment]
Thanks! Just to confirm, that fixes the problem for me.

**Comment by ax3l** [comment]
thanks for testing! :sparkles:
