### ISSUE TITLE
MSVC Warnings

### ISSUE THREAD

**Issue by ax3l** [wjakob/pybind11#77]
`master` as of 80a06745d31ea28e886423acf40f398b0227f73a currently generates warnings on MSVC:

- in `Debug` mode: https://ci.appveyor.com/project/wjakob/pybind11/build/1.0.141/job/c0yeltp07919w9dv https://ci.appveyor.com/project/wjakob/pybind11/build/1.0.141/job/xfv0nem114pjq3fh

```
NK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification [C:\projects\pybind11\example.vcxproj]

  Generating code
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xatomic.h(1621): warning C4702: unreachable code [C:\projects\pybind11\example.vcxproj]
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xatomic.h(1402): warning C4702: unreachable code [C:\projects\pybind11\example.vcxproj]
  Finished generating code
```

**Comment by ax3l** [comment]
cool, thanks!

**Comment by wjakob** [comment]
the xatomic warning remains, but that appeares to be a problem in MSVC itself.
