### ISSUE TITLE
PYBIND11_NOINLINE inline

### ISSUE THREAD

**Issue by ax3l** [wjakob/pybind11#79]
While trying to add `icc` support I stumbled upon several lines defining methods such as
```C++
PYBIND11_NOINLINE inline [...]
```

which makes probably no sense.

Is that intentionally?
Probably two individual `PYBIND11_NOINLINE` and  `PYBIND11_INLINE` macros would be more useful (using always only once of them when trying to force to (prevent) inlining).

**Comment by wjakob** [comment]
This is intentional (and there is a comment somewhere about it): what this does is to enforce 'inline' linkage (i.e. compiler does not complain about duplicate definitions from different compilation units), while forcing to generate function calls instead of actually inlining code. This is a size optimization to keep the final binary compact.

**Comment by ax3l** [comment]
I am very sure it is the opposite, at least on icc.

If you define *both* noinline and inline it will not only decide on *noinline* but does also throw a warning:
  http://eigen.tuxfamily.org/dox/DisableStupidWarnings_8h_source.html

**Comment by ax3l** [comment]
Example:
```
pybind11/cast.h(32): warning #2196: routine is both "inline" and "noinline"
  PYBIND11_NOINLINE inline internals &get_internals() {

pybind11/cast.h(47): warning #2196: routine is both "inline" and "noinline"
  PYBIND11_NOINLINE inline detail::type_info* get_type_info(PyTypeObject *type) {

[...]
```

**Comment by wjakob** [comment]
Yes, the goal is to have the code not be inlined, but to be compiled with inline *linkage* (note that this is a completely different concept -- it's about what the linker decides to do when it sees a symbol twice).

**Comment by ax3l** [comment]
oh I see, my fault!

seems still to be weird with icc, I will read a bit on the topic and what icc makes out of it.
