### ISSUE TITLE
PYBIND11_DECLARE_HOLDER_TYPE with std::shared_ptr

### ISSUE THREAD

**Issue by Vayu** [wjakob/pybind11#8]
The automatic transparent conversions do not seem to work for `std::shared_ptr`.

I looked at the example8 and it seems that `ref<T>` class there differs from `shared_ptr` in one apparently crucial aspect, it has user-defined conversion
```C++
operator T* () { return m_ptr; }
```
which allows it to be passed as the first argument to `cast` function.

I managed to get automatic conversion to work with `shared_ptr` by adding
```C++
diff --git a/include/pybind11/cast.h b/include/pybind11/cast.h
index 5fe9342..1cb4ff4 100644
--- a/include/pybind11/cast.h
+++ b/include/pybind11/cast.h
@@ -527,6 +527,12 @@ public:
     explicit operator type&() { return *(this->value); }
     explicit operator holder_type&() { return holder; }
     explicit operator holder_type*() { return &holder; }
+
+    using type_caster<type>::cast;
+    static PyObject *cast(const holder_type &src, return_value_policy policy, PyObject *parent) {
+      return type_caster<type>::cast(src.get(), policy, parent);
+    }
+
 protected:
     holder_type holder;
 };
```

But perhaps there is a better way?

**Comment by wjakob** [comment]
Thanks for catching that -- your patch looks good to me, I committed it.

**Comment by Vayu** [comment]
Thanks for the quick response
