### ISSUE TITLE
`#undef WITH_THREAD` not supported

### ISSUE THREAD

**Issue by FelipeLema** [wjakob/pybind11#81]
When `WITH_THREAD` is `#undef`ed in `$PYTHON_PREFIX/include/python2.7/pyconfig.h`.

    ./pybind11/include/pybind11/pybind11.h: In function ‘void pybind11::init_threading()’:
    ./pybind11/include/pybind11/pybind11.h:915:51: error: ‘PyEval_InitThreads’ was not declared in this scope
     inline void init_threading() { PyEval_InitThreads(); }

This problem is also probably in python3.x

How I got here? 3rd party custom python and I cannot change it.

**Comment by wjakob** [comment]
Ah, interesting -- can you submit a PR that removes these functions if WITH_THREAD is not defined? (it would need to also work for Python 3)

**Comment by FelipeLema** [comment]
Indeed, it looks like `#ifdef`ing that single call makes everything easy-peasy.

Let me build python3 with that `#define` and I'll do a pull request
