### ISSUE TITLE
What's the best way to deal with different types?

### ISSUE THREAD

**Issue by huntzhan** [wjakob/pybind11#84]
Suppose I want to process an `py::dict` instance which might contain different types of key/value pairs, i.e. `str/int`, `str/dict`. After reading `pybind11/pytypes.h`, I figure out that such problem could be solved by two steps:

1. invoke `handle::get_type` to get the type of instance.
2. pass `type_handle.ptr()` to `Py[Type]_Check` methods to detect the type.

I'm wondering if there is a better way to resolve the problem, such as function overloading or use some magic code to detect the type of of instance.

Thanks for your work, it's amazing!

**Comment by wjakob** [comment]
You can also cast it to the different wrapper classes (like ``pybind11::str``) and call their ``check()`` method, which does basically the same thing. Another way is to call ``(std::string) (<object>::get_type().str())`` and do something with the resulting expression.

**Comment by huntzhan** [comment]
> 

You can also cast it to the different wrapper classes (like pybind11::str) and call their check() method, which does basically the same thing. Another way is to call (std::string) (<object>::get_type().str()) and do something with the resulting expression.

Do you mean something like following code?

```cpp
for (auto item: dict) {
  auto key = item.first;
  if (pybind11::str(key).check()) {
    // do something on str.
  } else if (pybind11::int_(key).check()) {
    // do something on int.
  }
  ...
}

**Comment by wjakob** [comment]
Yes, for the first approach that would be the way to go.

For the second approach, you could build a more fancy dispatcher that maps the name of the type to a lambda function or so.

**Comment by huntzhan** [comment]
Ops! `pybind11::object(handle).check()` would not work, should be `pybind11::object(handle, true).check()`.

How about adding an `explicit` constructor?

**Comment by wjakob** [comment]
This is intentional -- the point is to force the user to think about for a moment if it is a borrowed or non-borrowed object (otherwise the reference counting will be incorrect)

**Comment by danielkoohmarey-bc** [comment]
Is this still the recommended approach for casting different types from a py dict into the corresponding c++ type?

**Comment by Skylion007** [comment]
@danielkoohmarey-bc Probably better to use isinstance functions to detect the type of handles. Most of the casters use them.
