### ISSUE TITLE
Type Identification by std::type_info* broken with multiple modules

### ISSUE THREAD

**Issue by andreasbuhr** [wjakob/pybind11#86]
Within pybind11, type identification is done using std::type_info*. Each type is identified with the pointer to its std::type_info. Unfortunately, this is broken. When using multiple modules, it may happen that the same type results in different std::type_info objects. This has already been noticed by pybind11 developers, see [cast.h:66](https://github.com/wjakob/pybind11/blob/master/include/pybind11/cast.h#L66). But the problem was not fixed in all instances.

We encountered the problem, getting the error message:

> TypeError: Unable to convert function return value to a Python type!

We wrote a reproducer for this problem and added it to the test infrastructure of pybind11, see our repository/branch [andreasbuhr/reproduce_multimodule_problem](https://github.com/andreasbuhr/pybind11/tree/reproduce_multimodule_problem). However, we did not create a pull request as we were not able to test our changes on other architectures than ours (Linux Mint, gcc 4.8.5). Feel free to merge anyway, if you like.

As a fix, we would suggest to use std::type_index instead of (std::type_info\*) to identify types, so using 
`std::unordered_map<const std::type_index, void*>` in [common.h:219](https://github.com/wjakob/pybind11/blob/master/include/pybind11/common.h#L219).
But we can not fully oversee the consequences of this change.

The initial test case was developed by @sdrave.

We would be very happy about a fix for this. If we can help in any way, let us know.

**Comment by wjakob** [comment]
Hi,

thanks for the report! Can you verify that the following patch (applies to the latest repository version) fixes the problem on your end?

Thanks,
Wenzel

[type_info_patch.txt](https://github.com/wjakob/pybind11/files/109449/type_info_patch.txt)

**Comment by sdrave** [comment]
Hi, I can confirm that the patch works fine, for the test case as well as for our actual code!
Thanks for the quick fix, Stephan

**Comment by wjakob** [comment]
sure think, thanks for the suggestion to use std::type_index

**Comment by andreasbuhr** [comment]
Thank you very much.
