### ISSUE TITLE
Problem with a buffer class (protected virtual destructor, reference counting)

### ISSUE THREAD

**Issue by nbigaouette** [wjakob/pybind11#87]
I have an existing OO code base that I'd like to expose some parts to Python. Note that I don't want to extend the classes with Python implementations. I simply want to _use_ the classes.

The classes inheritance goes something like this: `BaseObject -> DataBuffer` where:

- `BaseObject`: Implements reference counting, a default constructor and a virtual protected destructor.
- `DataBuffer`: Implements a buffer type (which can grow). Like `BaseObject`, it implements a default constructor and a virtual protected destructor. When a data buffer instance goes out of scope, the reference counting insures that the memory is freed.

I want to wrap another C++ class, say `Packet`, which defines a method that takes a `DataBuffer` _pointer_ as one of its arguments.

I believe the first step would be to create a wrapper for `DataBuffer` so that the `Packet`'s method can be exported too. Am I right?

I'm having issue creating that wrapper though. If I simply create expose the class using `py::class_<DataBuffer>`, I get errors like:
> error: ‘virtual DataBuffer::~DataBuffer()’ is protected

It's not a pure virtual method/destructor as there is an implementation in both `BaseObject` and `DataBuffer`. So I'm not sure that the doc's section [Overriding virtual functions in Python](http://pybind11.readthedocs.org/en/latest/advanced.html#overriding-virtual-functions-in-python) covers what I want to do.

I'm not sure how what to try next, so I looked at example 8 from which `MyObject1` has a protected virtual destructor. It seems I can make a parallel between the `MyObject1` class and my `DataBuffer`, and between `Object` and my `BaseObject`. [Lines 109 to 113](https://github.com/wjakob/pybind11/blob/b2c2c79240679463dd231c5430d8626bca3b596a/example/example8.cpp#L109-L113) might give a clue as how to do it, but I'm not sure how it would apply to my case as the `ref` template class in `object.h` is quite different then my `BaseObject`.

How should I approach that problem? Which doc or example would cover this best?

Thanks a lot! :)

**Comment by nbigaouette** [comment]
I identified the problem that I have.

The issue is that the objects constructors are virtual-protected. This means that, in C++, I cannot create a object like this:
```
BaseObject object;
```
This was a design decision done by the project owner. Even though there is a constructor, it does nothing. Objects should be created (in this project) like this:
```
BaseObject *object = BaseObject::New();
```

So the problems I had and trying to bypass was that, in Python, if I do this:
```
object = BaseObject()
```
then the object _is not valid_. It is in a weird limbo state since the allocator `BaseObject::New()` was never called!

Can I use pybind11 with such classes?

**Comment by wjakob** [comment]
The tricky part is probably not the constructor, but the destructor. By default, pybind11 uses ``std::unique_ptr`` to hold a reference to a C++ object. Once it reaches reference count zero on the Python side, the destructor of ``unique_ptr`` wants to call the constructor, which is protected in your case. So you'll have to switch to a different kind of holder type that works with the reference counting you are planning to implement. The ``Object`` and ``ref`` classes in the tutorials should really have all resources to explain how this works.

**Comment by nbigaouette** [comment]
Thanks, I'll take a closer look at the classes from example 8.

For now, I think the easiest will be to _not_ expose my classes to Python directly. Instead, I created a new class that has a single member variable which is a pointer to the class I want to expose. That way, I can define the new class' constructor to call the project `New()`. Once done, the original class' methods are exposed through the new class' pointer. I can also define a destructor in the new class that calls `Delete()` on the pointer.

It seems to be working fine for now. I'm not sure if this is going to work too when I'll have to define the wrappers for the classes inheriting the original one, but we'll see.

Meanwhile, I have another question for you. The docs describe [how to use the buffer protocol](http://pybind11.readthedocs.org/en/latest/advanced.html#buffer-protocol). I was able to use that to pass a Python `bytearray` and transform it to the project's buffer type. I simply use `pybind11::buffer` as the type of the wrapper lambda function that wraps/expose the required C++ method. But this is for _input_ argument: data coming from a Python `bytearray` that needs to be stored in a C++ object, similar to [what is done here](https://github.com/wjakob/pybind11/blob/b2c2c79240679463dd231c5430d8626bca3b596a/example/example7.cpp#L79-L87).

But I'm not sure how to do the opposite: If my lambda function takes `pybind11::buffer &b` as argument, how can I set `b`'s internal values so that when back in Python my argument is updated?

Thanks a lot!

**Comment by wjakob** [comment]
Please do take a look at the holder types, and specifically the ``ref`` example class. The use case you describe is **exactly** what this is intended for.

Regarding modifying the buffer: you can request() access and get a pointer and modify that. You can't change the structure of the array though (e.g. number of rows).
