### ISSUE TITLE
Pybind11 vectorization vs numpy broadcasting

### ISSUE THREAD

**Issue by SylvainCorlay** [wjakob/pybind11#89]
What is the reasoning behind implementing a custom vectorization in pybind11 over the numpy API and helpers to create vectorized functions? 

(See http://docs.scipy.org/doc/numpy-1.10.0/reference/c-api.ufunc.html and http://docs.scipy.org/doc/numpy-1.10.1/user/c-info.ufunc-tutorial.html).

**Comment by wjakob** [comment]
The vectorization in NumPy is just a nice syntax -- the actual loop executes in Python, so it's super-slow. The vectorization in Pybind11 is on the C++ side.

**Comment by SylvainCorlay** [comment]
Actually in both cases of the Python API (`np.vectorize`) and the C API (`PyUFunc_FromFuncAndData`), the loop is done in C. 

The former case is slow because of the overhead of the python function call, but the latter case (the C API to create Ufuncs) should be fast.

**Comment by wjakob** [comment]
np.vectorize run on a function bound using Pybind11 would involve passing through pybind11 for each function invocation (*lots* of python API calls), hence the slowness. pybind11::vectorize is there to avoid that. PyUFunc_FromFuncAndData is an alternative, but this does not have some of the amenities of stateful lambda closures -- take a look at the examples, and I'm sure you will agree that the approach in pybind11 is much more powerful.

**Comment by SylvainCorlay** [comment]
>  PyUFunc_FromFuncAndData is an alternative, but this does not have some of the amenities of stateful lambda closures -- take a look at the examples, and I'm sure you will agree that the approach in pybind11 is much more powerful.

Yes, that is *really* cool. Thanks

**Comment by jmabille** [comment]
I have a problem with broadcasting in pybind11. Here is a code sample to reproduce the problem:
```python
import test_pybind as tp
import numpy as np
x = np.array([1, 1, 1])
y = np.array([1, 1])[:, np.newaxis]
# Arrays are compatible for broadcasting
print(x + y)
# It also works with numpy ufuncs
print(np.logaddexp(x, y))
# But not with the pybind11 vectorize function
print(tp.vec_add(x, y))
```

**Comment by wjakob** [comment]
This would require a rewrite of pybind11::vectorize. It's not on my TODO list but patches are welcomed. (BTW: It's probably better if you create a separate ticket)

**Comment by jmabille** [comment]
Ok, I will open an new issue and probably start working on a patch tonight

**Comment by wjakob** [comment]
@jmabille Any news on this?

**Comment by jmabille** [comment]
I have a fix on a private repo in my company, I'm waiting for an authorization to push it on my public fork

**Comment by wjakob** [comment]
great -- please keep me posted.

**Comment by ax3l** [comment]
@JohanMabille following the links here - did you contrib this or is `py::vectorize` still the way to go? :)

**Comment by JohanMabille** [comment]
`py::vectorize` is still the way to go, but I think this part of the code (i.e. numpy related) has been rewritten many times, I don't know if the issue is still here.
