### ISSUE TITLE
builtin set type not supported

### ISSUE THREAD

**Issue by eudoxos** [wjakob/pybind11#9]
list and dict are suported by pybind11 (just like by boost::python), but support for the set builtin type is missing (also from boost::python -- see http://thread.gmane.org/gmane.comp.python.c++/15129). Could set be supported by pybind11?

**Comment by wjakob** [comment]
Good point -- I've committed support for std::set.

**Comment by eudoxos** [comment]
Great. For API similar to python, shouldn't insertion be called pybind11::set::add rather than insert?

**Comment by wjakob** [comment]
fair enough -- I renamed it.
