### ISSUE TITLE
PYBIND11_OBJECT_DEFAULT and  PYBIND11_OBJECT_CVT  documentation

### ISSUE THREAD

**Issue by DerThorsten** [wjakob/pybind11#90]
Hi,

I want to have a class 'MyArray<unsigned int DIM, class T>' which should maybe derive
from array_t<class T> .
I want to ensure that only numpyarrays with the correct dimension are converted.
Furthermore i would like to ensure that the numpy dtype must match the C++ type, if not,  it should not be convertible.

I guess i would need to use PYBIND11_OBJECT_DEFAULT and  PYBIND11_OBJECT_CVT
but so far i cannot make sense out of them.

Any suggestions?

**Comment by wjakob** [comment]
Sorry, I won't have time to document these any time soon as it is an internal API. These just declare the default constructors etc, but to find out more you'll have to read the source..
