### ISSUE TITLE
Exporting constants

### ISSUE THREAD

**Issue by nbigaouette** [wjakob/pybind11#92]
I need to access in Python constants defined in my header file similarely to `const uint32_t myConstant = 0x01020304;`.

Is it possible with pybind11? I've searched the doc and code about it but not sure it's implemented. It seems SWIG can do it (see http://www.swig.org/Doc1.3/SWIG.html#SWIG_nn12). This would be a nice addition.

Thanks!

**Comment by nbigaouette** [comment]
As a workaround, one can define a function that returns the constant.

For example:
```C++
py::module m("MyModule", "Python wrapper for MyModule");
// myConstant is defined as 'const int myConstant = 1;' in a header file.
m.def("myConstant", []() { return myConstant; });
```
will export the Python function `MyModule.myConstant()` which will return the needed constant.

**Comment by wjakob** [comment]
The syntax is ``xyz.attr("myConstant") = py::int_()``

**Comment by linrongbin16** [comment]
Hi @wjakob , is it available to bind **C++ non-arguments function** to **Python constant attributes/variables in module** ?

Is this sample code correct:
```C++

int my_constant() { return 0; }

PYBIND11_MODULE(constants, m) {
  m.attr("MY_CONSTANT") = py::int_([](){ return my_constant(); });
}
```

**Comment by jwuttke** [comment]
A simpler solution is described in https://pybind11-jagerman.readthedocs.io/en/stable/advanced.html:
```
m.attr("MY_CONSTANT") = py::int_(123);
```
