### ISSUE TITLE
C++11 enums with same int values are being confused on the Python side

### ISSUE THREAD

**Issue by nbigaouette** [wjakob/pybind11#93]
I have a C++11 enums that define some sizes. For example:

```C++
enum class MySize : uint32_t
{
	UNINITIALIZED = 0xFFFFFFFF,

	Header = 3 * sizeof(uint32_t),

	Header_Data = 0,
	Header_Total = Header + Header_Data,

	TypeFirst_Data = 0,
	TypeFirst_Total = Header + TypeFirst_Data
};
```

I can then use, in C++, the different sizes: `MySize::Header_Data`,  `MySize::Header_Total`, etc. I can also compare them in a same way: `MySize::Header_Data != MySize::TypeFirst_Data`.

I expose this enum to Python like this:
```C++
py::enum_<MySize>(m, "MySize")
    .value("UNINITIALIZED", MySize::UNINITIALIZED)
    .value("Header", MySize::Header)
    .value("Header_Data", MySize::Header_Data)
    .value("Header_Total", MySize::Header_Total)
    .value("TypeFirst_Data", MySize::TypeFirst_Data)
    .value("TypeFirst_Total", MySize::TypeFirst_Total);
```

The wrapper is compiled to a `CppWrapper` module (`CppWrapper.so`).

But then, in Python, if I print `CppWrapper.MySize.Header_Total` I get `MySize.TypeFirst_Total` instead of the expected `MySize.Header_Total`.

It seems that pybind11 gets confused with the enums.

If I switch the order of the `.value()` calls of `Header_Total` and `TypeFirst_Total`, I get the opposite behaviour; printing `CppWrapper.MySize.Header_Total` shows `MySize.Header_Total`.

Looking [at the code](https://github.com/wjakob/pybind11/blob/298183fac4e671ce77f5f002599888f7420b529f/include/pybind11/pybind11.h#L928-L935) I see that the `m_entries` is an unordered map with the key being the enum value. This is the cause of the problem as enums have no requirement to being unique...

**Comment by wjakob** [comment]
Yes, that's right -- printing the name of an enum will get confused if the mapping is not unique. 

I'm closing this ticket because there is no real solution to this problem. You'd have the same kinds of ambiguities in C++ if a black-box-function returns an enum value.
