### ISSUE TITLE
Functions defined in pybind11 extension modules don't have a `__module__` attribute

### ISSUE THREAD

**Issue by SylvainCorlay** [wjakob/pybind11#95]
It seems that wrappers defined with pybind11 don't have their `__module__` attribute set.

**Comment by wjakob** [comment]
Can you explain a bit more how this manifests itself? Is there a problem with a piece of software, etc.?

**Comment by SylvainCorlay** [comment]
I am using sphinx to generate documentation for an extension module that was built with pybind11. It seems that autodoc relies on `__module__` to be defined for functions, and `__package__` to be defined for modules...

While sphinx autodoc sees the docstrings of the C extension modules defined with pybind, it has trouble accessing the free functions defined in it.

**Comment by SylvainCorlay** [comment]
(Should we carry on the conversation on #96 since there were more comments there.)

**Comment by wjakob** [comment]
sure
